`timescale 1ns / 1ps
// PCIe Wrapper
// Wraps Xilinx UltraScale PCIe Gen2x4 IP + AXI-MM to AXI-Lite bridge
// The actual IP is generated by Vivado TCL script; this module provides
// the interface used by ate_top

module pcie_wrapper
    import ate_pkg::*;
(
    // PCIe reference clock (125 MHz from PXIe backplane or G2 oscillator)
    input  logic        pcie_refclk_p,
    input  logic        pcie_refclk_n,

    // PCIe lanes
    output logic [3:0]  pcie_tx_p,
    output logic [3:0]  pcie_tx_n,
    input  logic [3:0]  pcie_rx_p,
    input  logic [3:0]  pcie_rx_n,

    // PCIe reset
    input  logic        pcie_perst_n,

    // User clock output (derived from PCIe IP, typically 125 or 250 MHz)
    output logic        user_clk,
    output logic        user_reset_n,
    output logic        user_lnk_up,

    // AXI4-Lite master interface (BAR0 → register space)
    output logic [AXI_ADDR_W-1:0] m_axi_awaddr,
    output logic [2:0]            m_axi_awprot,
    output logic                   m_axi_awvalid,
    input  logic                   m_axi_awready,
    output logic [AXI_DATA_W-1:0] m_axi_wdata,
    output logic [3:0]            m_axi_wstrb,
    output logic                   m_axi_wvalid,
    input  logic                   m_axi_wready,
    input  logic [1:0]            m_axi_bresp,
    input  logic                   m_axi_bvalid,
    output logic                   m_axi_bready,
    output logic [AXI_ADDR_W-1:0] m_axi_araddr,
    output logic [2:0]            m_axi_arprot,
    output logic                   m_axi_arvalid,
    input  logic                   m_axi_arready,
    input  logic [AXI_DATA_W-1:0] m_axi_rdata,
    input  logic [1:0]            m_axi_rresp,
    input  logic                   m_axi_rvalid,
    output logic                   m_axi_rready,

    // DMA interface (for vector memory and capture data)
    // AXI4-MM to DDR3 (simplified: read/write channels)
    output logic        dma_h2c_valid,  // Host→Card data valid
    output logic [31:0] dma_h2c_addr,
    output logic [127:0]dma_h2c_data,
    input  logic        dma_h2c_ready,

    input  logic        dma_c2h_valid,  // Card→Host data valid
    input  logic [127:0]dma_c2h_data,
    output logic        dma_c2h_ready,

    // Interrupt
    input  logic [3:0]  irq_req,
    output logic        irq_ack
);

    // ================================================================
    // PCIe refclk buffer
    // ================================================================
    logic pcie_refclk;

    IBUFDS_GTE3 u_refclk_buf (
        .O     (pcie_refclk),
        .ODIV2 (),
        .CEB   (1'b0),
        .I     (pcie_refclk_p),
        .IB    (pcie_refclk_n)
    );

    // ================================================================
    // Xilinx PCIe IP instantiation placeholder
    // ================================================================
    // The actual IP (pcie3_ultrascale or xdma) is generated by:
    //   FPGA/project/generate_ips.tcl
    //
    // Configuration:
    //   - PCIe Gen2 x4
    //   - BAR0: 64KB AXI4-Lite (register space)
    //   - BAR1: 256MB AXI4-MM (DMA to DDR3, optional)
    //   - MSI-X: 16 vectors
    //   - Device ID: custom (matches ATE card)
    //
    // For initial bring-up without PCIe, the AXI-Lite interface can be
    // driven by VIO/JTAG-AXI IP instead.

    // Temporary: tie off outputs for synthesis without IP
    assign user_clk      = 1'b0;
    assign user_reset_n  = 1'b0;
    assign user_lnk_up   = 1'b0;
    assign m_axi_awaddr  = '0;
    assign m_axi_awprot  = '0;
    assign m_axi_awvalid = 1'b0;
    assign m_axi_wdata   = '0;
    assign m_axi_wstrb   = '0;
    assign m_axi_wvalid  = 1'b0;
    assign m_axi_bready  = 1'b1;
    assign m_axi_araddr  = '0;
    assign m_axi_arprot  = '0;
    assign m_axi_arvalid = 1'b0;
    assign m_axi_rready  = 1'b1;
    assign dma_h2c_valid = 1'b0;
    assign dma_h2c_addr  = '0;
    assign dma_h2c_data  = '0;
    assign dma_c2h_ready = 1'b1;
    assign irq_ack       = 1'b0;

    // When PCIe IP is generated, replace above with:
    // xdma_0 u_xdma ( ... );
    // or
    // pcie3_ultrascale_0 u_pcie ( ... );

endmodule
