## ============================================================================
## Auto-generated pin assignments: ADATE305 LVDS signals (16 sites)
## Generated from Ku035_Board + DLC_Board netlist cross-reference
## ============================================================================

## --- Site 1 (ADATE305 chip 0, ch 0) ---
# set_property PACKAGE_PIN E15    [get_ports {s1_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s1_rcv_1_p}]
# set_property PACKAGE_PIN D15    [get_ports {s1_rcv_1_n}]
# set_property PACKAGE_PIN B15    [get_ports {s1_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s1_comp_qh_0_p}]
# set_property PACKAGE_PIN A15    [get_ports {s1_comp_qh_0_n}]
# set_property PACKAGE_PIN B14    [get_ports {s1_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s1_comp_ql_0_p}]
# set_property PACKAGE_PIN A14    [get_ports {s1_comp_ql_0_n}]
# set_property PACKAGE_PIN D14    [get_ports {s1_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s1_comp_ql_1_p}]
# set_property PACKAGE_PIN C14    [get_ports {s1_comp_ql_1_n}]

## --- Site 2 (ADATE305 chip 0, ch 1) ---
# set_property PACKAGE_PIN G15    [get_ports {s2_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s2_data_0_p}]
# set_property PACKAGE_PIN G14    [get_ports {s2_data_0_n}]
# set_property PACKAGE_PIN AA20   [get_ports {s2_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s2_data_1_p}]
# set_property PACKAGE_PIN AB20   [get_ports {s2_data_1_n}]
# set_property PACKAGE_PIN H17    [get_ports {s2_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s2_rcv_0_p}]
# set_property PACKAGE_PIN H16    [get_ports {s2_rcv_0_n}]

## --- Site 3 (ADATE305 chip 1, ch 0) ---
# set_property PACKAGE_PIN V21    [get_ports {s3_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_data_0_p}]
# set_property PACKAGE_PIN W21    [get_ports {s3_data_0_n}]
# set_property PACKAGE_PIN AB24   [get_ports {s3_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_data_1_p}]
# set_property PACKAGE_PIN AC24   [get_ports {s3_data_1_n}]
# set_property PACKAGE_PIN V22    [get_ports {s3_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_rcv_0_p}]
# set_property PACKAGE_PIN V23    [get_ports {s3_rcv_0_n}]
# set_property PACKAGE_PIN AD25   [get_ports {s3_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_rcv_1_p}]
# set_property PACKAGE_PIN AD26   [get_ports {s3_rcv_1_n}]
# set_property PACKAGE_PIN AF30   [get_ports {s3_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_comp_qh_0_p}]
# set_property PACKAGE_PIN AG30   [get_ports {s3_comp_qh_0_n}]
# set_property PACKAGE_PIN AG31   [get_ports {s3_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_comp_qh_1_p}]
# set_property PACKAGE_PIN AG32   [get_ports {s3_comp_qh_1_n}]
# set_property PACKAGE_PIN Y23    [get_ports {s3_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_comp_ql_0_p}]
# set_property PACKAGE_PIN AA23   [get_ports {s3_comp_ql_0_n}]
# set_property PACKAGE_PIN AF29   [get_ports {s3_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s3_comp_ql_1_p}]
# set_property PACKAGE_PIN AG29   [get_ports {s3_comp_ql_1_n}]

## --- Site 4 (ADATE305 chip 1, ch 1) ---
# set_property PACKAGE_PIN AC22   [get_ports {s4_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_data_0_p}]
# set_property PACKAGE_PIN AC23   [get_ports {s4_data_0_n}]
# set_property PACKAGE_PIN AG12   [get_ports {s4_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_data_1_p}]
# set_property PACKAGE_PIN AH12   [get_ports {s4_data_1_n}]
# set_property PACKAGE_PIN AB21   [get_ports {s4_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_rcv_0_p}]
# set_property PACKAGE_PIN AC21   [get_ports {s4_rcv_0_n}]
# set_property PACKAGE_PIN AF9    [get_ports {s4_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_rcv_1_p}]
# set_property PACKAGE_PIN AG9    [get_ports {s4_rcv_1_n}]
# set_property PACKAGE_PIN AD11   [get_ports {s4_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_comp_qh_0_p}]
# set_property PACKAGE_PIN AE11   [get_ports {s4_comp_qh_0_n}]
# set_property PACKAGE_PIN AE12   [get_ports {s4_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_comp_qh_1_p}]
# set_property PACKAGE_PIN AF12   [get_ports {s4_comp_qh_1_n}]
# set_property PACKAGE_PIN AD10   [get_ports {s4_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_comp_ql_0_p}]
# set_property PACKAGE_PIN AE10   [get_ports {s4_comp_ql_0_n}]
# set_property PACKAGE_PIN AE13   [get_ports {s4_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s4_comp_ql_1_p}]
# set_property PACKAGE_PIN AF13   [get_ports {s4_comp_ql_1_n}]

## --- Site 5 (ADATE305 chip 2, ch 0) ---
# set_property PACKAGE_PIN B17    [get_ports {s5_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_data_0_p}]
# set_property PACKAGE_PIN B16    [get_ports {s5_data_0_n}]
# set_property PACKAGE_PIN D20    [get_ports {s5_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_data_1_p}]
# set_property PACKAGE_PIN D21    [get_ports {s5_data_1_n}]
# set_property PACKAGE_PIN C18    [get_ports {s5_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_rcv_0_p}]
# set_property PACKAGE_PIN C17    [get_ports {s5_rcv_0_n}]
# set_property PACKAGE_PIN E20    [get_ports {s5_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_rcv_1_p}]
# set_property PACKAGE_PIN E21    [get_ports {s5_rcv_1_n}]
# set_property PACKAGE_PIN C19    [get_ports {s5_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_comp_qh_0_p}]
# set_property PACKAGE_PIN B19    [get_ports {s5_comp_qh_0_n}]
# set_property PACKAGE_PIN D19    [get_ports {s5_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_comp_qh_1_p}]
# set_property PACKAGE_PIN D18    [get_ports {s5_comp_qh_1_n}]
# set_property PACKAGE_PIN A19    [get_ports {s5_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_comp_ql_0_p}]
# set_property PACKAGE_PIN A18    [get_ports {s5_comp_ql_0_n}]
# set_property PACKAGE_PIN C21    [get_ports {s5_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s5_comp_ql_1_p}]
# set_property PACKAGE_PIN C22    [get_ports {s5_comp_ql_1_n}]

## --- Site 6 (ADATE305 chip 2, ch 1) ---
# set_property PACKAGE_PIN G20    [get_ports {s6_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s6_data_0_p}]
# set_property PACKAGE_PIN F20    [get_ports {s6_data_0_n}]
# set_property PACKAGE_PIN F18    [get_ports {s6_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s6_rcv_0_p}]
# set_property PACKAGE_PIN F17    [get_ports {s6_rcv_0_n}]
# set_property PACKAGE_PIN J15    [get_ports {s6_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s6_comp_qh_0_p}]
# set_property PACKAGE_PIN J14    [get_ports {s6_comp_qh_0_n}]
# set_property PACKAGE_PIN G17    [get_ports {s6_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s6_comp_ql_0_p}]
# set_property PACKAGE_PIN G16    [get_ports {s6_comp_ql_0_n}]

## --- Site 7 (ADATE305 chip 3, ch 0) ---
# set_property PACKAGE_PIN Y26    [get_ports {s7_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_data_1_p}]
# set_property PACKAGE_PIN Y27    [get_ports {s7_data_1_n}]
# set_property PACKAGE_PIN W23    [get_ports {s7_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_rcv_0_p}]
# set_property PACKAGE_PIN W24    [get_ports {s7_rcv_0_n}]
# set_property PACKAGE_PIN AA27   [get_ports {s7_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_rcv_1_p}]
# set_property PACKAGE_PIN AB27   [get_ports {s7_rcv_1_n}]
# set_property PACKAGE_PIN W25    [get_ports {s7_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_comp_qh_0_p}]
# set_property PACKAGE_PIN Y25    [get_ports {s7_comp_qh_0_n}]
# set_property PACKAGE_PIN W28    [get_ports {s7_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_comp_qh_1_p}]
# set_property PACKAGE_PIN Y28    [get_ports {s7_comp_qh_1_n}]
# set_property PACKAGE_PIN AA24   [get_ports {s7_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_comp_ql_0_p}]
# set_property PACKAGE_PIN AA25   [get_ports {s7_comp_ql_0_n}]
# set_property PACKAGE_PIN V26    [get_ports {s7_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s7_comp_ql_1_p}]
# set_property PACKAGE_PIN W26    [get_ports {s7_comp_ql_1_n}]

## --- Site 8 (ADATE305 chip 3, ch 1) ---
# set_property PACKAGE_PIN AB25   [get_ports {s8_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_data_0_p}]
# set_property PACKAGE_PIN AB26   [get_ports {s8_data_0_n}]
# set_property PACKAGE_PIN AM11   [get_ports {s8_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_data_1_p}]
# set_property PACKAGE_PIN AN11   [get_ports {s8_data_1_n}]
# set_property PACKAGE_PIN AC28   [get_ports {s8_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_rcv_0_p}]
# set_property PACKAGE_PIN AD28   [get_ports {s8_rcv_0_n}]
# set_property PACKAGE_PIN AL10   [get_ports {s8_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_rcv_1_p}]
# set_property PACKAGE_PIN AM10   [get_ports {s8_rcv_1_n}]
# set_property PACKAGE_PIN AN13   [get_ports {s8_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_comp_qh_0_p}]
# set_property PACKAGE_PIN AP13   [get_ports {s8_comp_qh_0_n}]
# set_property PACKAGE_PIN AP11   [get_ports {s8_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_comp_qh_1_p}]
# set_property PACKAGE_PIN AP10   [get_ports {s8_comp_qh_1_n}]
# set_property PACKAGE_PIN AD29   [get_ports {s8_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_comp_ql_0_p}]
# set_property PACKAGE_PIN AE30   [get_ports {s8_comp_ql_0_n}]
# set_property PACKAGE_PIN AM12   [get_ports {s8_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s8_comp_ql_1_p}]
# set_property PACKAGE_PIN AN12   [get_ports {s8_comp_ql_1_n}]

## --- Site 9 (ADATE305 chip 4, ch 0) ---
# set_property PACKAGE_PIN B29    [get_ports {s9_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_data_0_p}]
# set_property PACKAGE_PIN A29    [get_ports {s9_data_0_n}]
# set_property PACKAGE_PIN D24    [get_ports {s9_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_data_1_p}]
# set_property PACKAGE_PIN C24    [get_ports {s9_data_1_n}]
# set_property PACKAGE_PIN C27    [get_ports {s9_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_rcv_0_p}]
# set_property PACKAGE_PIN B27    [get_ports {s9_rcv_0_n}]
# set_property PACKAGE_PIN E26    [get_ports {s9_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_rcv_1_p}]
# set_property PACKAGE_PIN D26    [get_ports {s9_rcv_1_n}]
# set_property PACKAGE_PIN B21    [get_ports {s9_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_comp_qh_0_p}]
# set_property PACKAGE_PIN B22    [get_ports {s9_comp_qh_0_n}]
# set_property PACKAGE_PIN F23    [get_ports {s9_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_comp_qh_1_p}]
# set_property PACKAGE_PIN F24    [get_ports {s9_comp_qh_1_n}]
# set_property PACKAGE_PIN B20    [get_ports {s9_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_comp_ql_0_p}]
# set_property PACKAGE_PIN A20    [get_ports {s9_comp_ql_0_n}]
# set_property PACKAGE_PIN E25    [get_ports {s9_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s9_comp_ql_1_p}]
# set_property PACKAGE_PIN D25    [get_ports {s9_comp_ql_1_n}]

## --- Site 10 (ADATE305 chip 4, ch 1) ---
# set_property PACKAGE_PIN K16    [get_ports {s10_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s10_data_0_p}]
# set_property PACKAGE_PIN J16    [get_ports {s10_data_0_n}]
# set_property PACKAGE_PIN L15    [get_ports {s10_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s10_rcv_0_p}]
# set_property PACKAGE_PIN K15    [get_ports {s10_rcv_0_n}]
# set_property PACKAGE_PIN G19    [get_ports {s10_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s10_comp_qh_0_p}]
# set_property PACKAGE_PIN F19    [get_ports {s10_comp_qh_0_n}]
# set_property PACKAGE_PIN T22    [get_ports {s10_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s10_comp_qh_1_p}]
# set_property PACKAGE_PIN T23    [get_ports {s10_comp_qh_1_n}]
# set_property PACKAGE_PIN G22    [get_ports {s10_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s10_comp_ql_0_p}]
# set_property PACKAGE_PIN F22    [get_ports {s10_comp_ql_0_n}]
# set_property PACKAGE_PIN U21    [get_ports {s10_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s10_comp_ql_1_p}]
# set_property PACKAGE_PIN U22    [get_ports {s10_comp_ql_1_n}]

## --- Site 11 (ADATE305 chip 5, ch 0) ---
# set_property PACKAGE_PIN V29    [get_ports {s11_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_data_0_p}]
# set_property PACKAGE_PIN W29    [get_ports {s11_data_0_n}]
# set_property PACKAGE_PIN W30    [get_ports {s11_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_data_1_p}]
# set_property PACKAGE_PIN Y30    [get_ports {s11_data_1_n}]
# set_property PACKAGE_PIN V31    [get_ports {s11_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_rcv_0_p}]
# set_property PACKAGE_PIN W31    [get_ports {s11_rcv_0_n}]
# set_property PACKAGE_PIN AA29   [get_ports {s11_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_rcv_1_p}]
# set_property PACKAGE_PIN AB29   [get_ports {s11_rcv_1_n}]
# set_property PACKAGE_PIN V27    [get_ports {s11_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_comp_qh_0_p}]
# set_property PACKAGE_PIN V28    [get_ports {s11_comp_qh_0_n}]
# set_property PACKAGE_PIN AC31   [get_ports {s11_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_comp_qh_1_p}]
# set_property PACKAGE_PIN AC32   [get_ports {s11_comp_qh_1_n}]
# set_property PACKAGE_PIN U24    [get_ports {s11_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_comp_ql_0_p}]
# set_property PACKAGE_PIN U25    [get_ports {s11_comp_ql_0_n}]
# set_property PACKAGE_PIN AA32   [get_ports {s11_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s11_comp_ql_1_p}]
# set_property PACKAGE_PIN AB32   [get_ports {s11_comp_ql_1_n}]

## --- Site 12 (ADATE305 chip 5, ch 1) ---
# set_property PACKAGE_PIN AN8    [get_ports {s12_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_data_0_p}]
# set_property PACKAGE_PIN AP8    [get_ports {s12_data_0_n}]
# set_property PACKAGE_PIN AK8    [get_ports {s12_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_data_1_p}]
# set_property PACKAGE_PIN AL8    [get_ports {s12_data_1_n}]
# set_property PACKAGE_PIN AK10   [get_ports {s12_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_rcv_0_p}]
# set_property PACKAGE_PIN AL9    [get_ports {s12_rcv_0_n}]
# set_property PACKAGE_PIN AJ9    [get_ports {s12_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_rcv_1_p}]
# set_property PACKAGE_PIN AJ8    [get_ports {s12_rcv_1_n}]
# set_property PACKAGE_PIN AN9    [get_ports {s12_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_comp_qh_0_p}]
# set_property PACKAGE_PIN AP9    [get_ports {s12_comp_qh_0_n}]
# set_property PACKAGE_PIN AF10   [get_ports {s12_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_comp_qh_1_p}]
# set_property PACKAGE_PIN AG10   [get_ports {s12_comp_qh_1_n}]
# set_property PACKAGE_PIN AC33   [get_ports {s12_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_comp_ql_0_p}]
# set_property PACKAGE_PIN AD33   [get_ports {s12_comp_ql_0_n}]
# set_property PACKAGE_PIN AH9    [get_ports {s12_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s12_comp_ql_1_p}]
# set_property PACKAGE_PIN AH8    [get_ports {s12_comp_ql_1_n}]

## --- Site 13 (ADATE305 chip 6, ch 0) ---
# set_property PACKAGE_PIN B25    [get_ports {s13_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_data_0_p}]
# set_property PACKAGE_PIN A25    [get_ports {s13_data_0_n}]
# set_property PACKAGE_PIN C26    [get_ports {s13_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_data_1_p}]
# set_property PACKAGE_PIN B26    [get_ports {s13_data_1_n}]
# set_property PACKAGE_PIN B24    [get_ports {s13_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_rcv_0_p}]
# set_property PACKAGE_PIN A24    [get_ports {s13_rcv_0_n}]
# set_property PACKAGE_PIN A27    [get_ports {s13_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_rcv_1_p}]
# set_property PACKAGE_PIN A28    [get_ports {s13_rcv_1_n}]
# set_property PACKAGE_PIN E22    [get_ports {s13_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_comp_qh_0_p}]
# set_property PACKAGE_PIN E23    [get_ports {s13_comp_qh_0_n}]
# set_property PACKAGE_PIN E28    [get_ports {s13_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_comp_qh_1_p}]
# set_property PACKAGE_PIN D29    [get_ports {s13_comp_qh_1_n}]
# set_property PACKAGE_PIN D23    [get_ports {s13_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_comp_ql_0_p}]
# set_property PACKAGE_PIN C23    [get_ports {s13_comp_ql_0_n}]
# set_property PACKAGE_PIN D28    [get_ports {s13_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s13_comp_ql_1_p}]
# set_property PACKAGE_PIN C28    [get_ports {s13_comp_ql_1_n}]

## --- Site 14 (ADATE305 chip 6, ch 1) ---
# set_property PACKAGE_PIN H19    [get_ports {s14_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_data_0_p}]
# set_property PACKAGE_PIN H18    [get_ports {s14_data_0_n}]
# set_property PACKAGE_PIN J19    [get_ports {s14_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_data_1_p}]
# set_property PACKAGE_PIN J18    [get_ports {s14_data_1_n}]
# set_property PACKAGE_PIN H21    [get_ports {s14_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_rcv_0_p}]
# set_property PACKAGE_PIN G21    [get_ports {s14_rcv_0_n}]
# set_property PACKAGE_PIN K18    [get_ports {s14_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_rcv_1_p}]
# set_property PACKAGE_PIN K17    [get_ports {s14_rcv_1_n}]
# set_property PACKAGE_PIN F27    [get_ports {s14_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_comp_qh_0_p}]
# set_property PACKAGE_PIN E27    [get_ports {s14_comp_qh_0_n}]
# set_property PACKAGE_PIN U26    [get_ports {s14_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_comp_qh_1_p}]
# set_property PACKAGE_PIN U27    [get_ports {s14_comp_qh_1_n}]
# set_property PACKAGE_PIN G24    [get_ports {s14_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_comp_ql_0_p}]
# set_property PACKAGE_PIN F25    [get_ports {s14_comp_ql_0_n}]
# set_property PACKAGE_PIN L19    [get_ports {s14_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s14_comp_ql_1_p}]
# set_property PACKAGE_PIN L18    [get_ports {s14_comp_ql_1_n}]

## --- Site 15 (ADATE305 chip 7, ch 0) ---
# set_property PACKAGE_PIN Y31    [get_ports {s15_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_data_0_p}]
# set_property PACKAGE_PIN Y32    [get_ports {s15_data_0_n}]
# set_property PACKAGE_PIN AA34   [get_ports {s15_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_data_1_p}]
# set_property PACKAGE_PIN AB34   [get_ports {s15_data_1_n}]
# set_property PACKAGE_PIN W33    [get_ports {s15_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_rcv_0_p}]
# set_property PACKAGE_PIN Y33    [get_ports {s15_rcv_0_n}]
# set_property PACKAGE_PIN AB30   [get_ports {s15_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_rcv_1_p}]
# set_property PACKAGE_PIN AB31   [get_ports {s15_rcv_1_n}]
# set_property PACKAGE_PIN U34    [get_ports {s15_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_comp_qh_0_p}]
# set_property PACKAGE_PIN V34    [get_ports {s15_comp_qh_0_n}]
# set_property PACKAGE_PIN AD30   [get_ports {s15_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_comp_qh_1_p}]
# set_property PACKAGE_PIN AD31   [get_ports {s15_comp_qh_1_n}]
# set_property PACKAGE_PIN V33    [get_ports {s15_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_comp_ql_0_p}]
# set_property PACKAGE_PIN W34    [get_ports {s15_comp_ql_0_n}]
# set_property PACKAGE_PIN AC34   [get_ports {s15_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s15_comp_ql_1_p}]
# set_property PACKAGE_PIN AD34   [get_ports {s15_comp_ql_1_n}]

## --- Site 16 (ADATE305 chip 7, ch 1) ---
# set_property PACKAGE_PIN AK12   [get_ports {s16_data_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_data_0_p}]
# set_property PACKAGE_PIN AL12   [get_ports {s16_data_0_n}]
# set_property PACKAGE_PIN AH13   [get_ports {s16_data_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_data_1_p}]
# set_property PACKAGE_PIN AJ13   [get_ports {s16_data_1_n}]
# set_property PACKAGE_PIN AK13   [get_ports {s16_rcv_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_rcv_0_p}]
# set_property PACKAGE_PIN AL13   [get_ports {s16_rcv_0_n}]
# set_property PACKAGE_PIN AG11   [get_ports {s16_rcv_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_rcv_1_p}]
# set_property PACKAGE_PIN AH11   [get_ports {s16_rcv_1_n}]
# set_property PACKAGE_PIN AE33   [get_ports {s16_comp_qh_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_comp_qh_0_p}]
# set_property PACKAGE_PIN AF34   [get_ports {s16_comp_qh_0_n}]
# set_property PACKAGE_PIN AE8    [get_ports {s16_comp_qh_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_comp_qh_1_p}]
# set_property PACKAGE_PIN AF8    [get_ports {s16_comp_qh_1_n}]
# set_property PACKAGE_PIN AF33   [get_ports {s16_comp_ql_0_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_comp_ql_0_p}]
# set_property PACKAGE_PIN AG34   [get_ports {s16_comp_ql_0_n}]
# set_property PACKAGE_PIN AD9    [get_ports {s16_comp_ql_1_p}]
# set_property IOSTANDARD LVDS [get_ports {s16_comp_ql_1_p}]
# set_property PACKAGE_PIN AD8    [get_ports {s16_comp_ql_1_n}]

## Total mapped signals: 224
