// DDR3 Memory Controller Wrapper
// Wraps Xilinx MIG IP and provides simplified read/write interfaces
// for Vector Memory, Source/Capture memory, and DMA access

module ddr3_wrapper
    import ate_pkg::*;
(
    input  logic        sys_clk_200,    // 200 MHz reference for MIG
    input  logic        sys_rst_n,

    // MIG UI clock output (typically 100 MHz)
    output logic        ui_clk,
    output logic        ui_rst_n,
    output logic        init_calib_complete,

    // DDR3 physical interface (directly to DDR3 SDRAM pins)
    // These are directly connected to package pins; defined in constraints
    output logic [15:0] ddr3_addr,
    output logic [2:0]  ddr3_ba,
    output logic        ddr3_ras_n,
    output logic        ddr3_cas_n,
    output logic        ddr3_we_n,
    output logic        ddr3_reset_n,
    output logic [0:0]  ddr3_ck_p,
    output logic [0:0]  ddr3_ck_n,
    output logic [0:0]  ddr3_cke,
    output logic [0:0]  ddr3_cs_n,
    output logic [7:0]  ddr3_dm,
    inout  wire  [63:0] ddr3_dq,
    inout  wire  [7:0]  ddr3_dqs_p,
    inout  wire  [7:0]  ddr3_dqs_n,
    output logic [0:0]  ddr3_odt,

    // Port A: Vector Memory read (from vector_prefetch)
    input  logic                      pa_rd_req,
    input  logic [VECTOR_ADDR_W-1:0] pa_rd_addr,
    output logic [VECTOR_WIDTH-1:0]  pa_rd_data,
    output logic                      pa_rd_valid,
    output logic                      pa_rd_ready,

    // Port B: DMA write (from PCIe host → vector memory)
    input  logic                      pb_wr_req,
    input  logic [VECTOR_ADDR_W-1:0] pb_wr_addr,
    input  logic [VECTOR_WIDTH-1:0]  pb_wr_data,
    output logic                      pb_wr_ready
);

    // ================================================================
    // MIG IP instantiation placeholder
    // ================================================================
    // Generated by: FPGA/project/generate_ips.tcl
    //
    // Configuration:
    //   - DDR3-1600 (800 MHz DDR)
    //   - Data width: 64-bit
    //   - Capacity: depends on installed SDRAM (512MB~2GB)
    //   - AXI4 interface, 128-bit data width
    //   - UI clock: 200 MHz (1/4 DDR clock)
    //   - Reference clock: 200 MHz (sys_clk)
    //   - Banks: 44, 45, 46

    // ================================================================
    // Address mapping
    // ================================================================
    // Vector memory: 128-bit per vector
    // DDR3 byte address = vector_addr × 16 (128 bit = 16 bytes)
    //
    // Memory map:
    //   0x0000_0000 ~ 0x0FFF_FFFF: Vector storage (256MB = 16M vectors)
    //   0x1000_0000 ~ 0x13FF_FFFF: Source waveform (64MB)
    //   0x1400_0000 ~ 0x17FF_FFFF: Capture buffer (64MB)
    //   0x1800_0000 ~ 0x1BFF_FFFF: Reserved

    // ================================================================
    // AXI4 interface signals (to MIG IP)
    // ================================================================
    // AXI4 Write
    logic [3:0]   axi_awid;
    logic [31:0]  axi_awaddr;
    logic [7:0]   axi_awlen;
    logic [2:0]   axi_awsize;
    logic [1:0]   axi_awburst;
    logic         axi_awvalid, axi_awready;
    logic [127:0] axi_wdata;
    logic [15:0]  axi_wstrb;
    logic         axi_wlast;
    logic         axi_wvalid, axi_wready;
    logic [3:0]   axi_bid;
    logic [1:0]   axi_bresp;
    logic         axi_bvalid, axi_bready;

    // AXI4 Read
    logic [3:0]   axi_arid;
    logic [31:0]  axi_araddr;
    logic [7:0]   axi_arlen;
    logic [2:0]   axi_arsize;
    logic [1:0]   axi_arburst;
    logic         axi_arvalid, axi_arready;
    logic [3:0]   axi_rid;
    logic [127:0] axi_rdata;
    logic [1:0]   axi_rresp;
    logic         axi_rlast;
    logic         axi_rvalid, axi_rready;

    // ================================================================
    // Port A: Vector read → AXI4 read channel
    // ================================================================
    typedef enum logic [1:0] {
        RD_IDLE,
        RD_ADDR,
        RD_DATA
    } rd_state_t;

    rd_state_t rd_state;

    always_ff @(posedge ui_clk or negedge ui_rst_n) begin
        if (!ui_rst_n) begin
            rd_state    <= RD_IDLE;
            axi_arvalid <= 1'b0;
            axi_rready  <= 1'b0;
            pa_rd_valid <= 1'b0;
            pa_rd_data  <= '0;
            pa_rd_ready <= 1'b1;
        end else begin
            pa_rd_valid <= 1'b0;

            case (rd_state)
                RD_IDLE: begin
                    pa_rd_ready <= 1'b1;
                    if (pa_rd_req) begin
                        axi_araddr  <= {pa_rd_addr, 4'b0000}; // ×16 bytes
                        axi_arid    <= 4'd0;
                        axi_arlen   <= 8'd0;   // Single beat
                        axi_arsize  <= 3'b100;  // 16 bytes
                        axi_arburst <= 2'b01;   // INCR
                        axi_arvalid <= 1'b1;
                        pa_rd_ready <= 1'b0;
                        rd_state    <= RD_ADDR;
                    end
                end

                RD_ADDR: begin
                    if (axi_arready) begin
                        axi_arvalid <= 1'b0;
                        axi_rready  <= 1'b1;
                        rd_state    <= RD_DATA;
                    end
                end

                RD_DATA: begin
                    if (axi_rvalid) begin
                        pa_rd_data  <= axi_rdata;
                        pa_rd_valid <= 1'b1;
                        axi_rready  <= 1'b0;
                        rd_state    <= RD_IDLE;
                    end
                end
            endcase
        end
    end

    // ================================================================
    // Port B: DMA write → AXI4 write channel
    // ================================================================
    typedef enum logic [1:0] {
        WR_IDLE,
        WR_ADDR,
        WR_DATA,
        WR_RESP
    } wr_state_t;

    wr_state_t wr_state;

    always_ff @(posedge ui_clk or negedge ui_rst_n) begin
        if (!ui_rst_n) begin
            wr_state    <= WR_IDLE;
            axi_awvalid <= 1'b0;
            axi_wvalid  <= 1'b0;
            axi_bready  <= 1'b0;
            pb_wr_ready <= 1'b1;
        end else begin
            case (wr_state)
                WR_IDLE: begin
                    pb_wr_ready <= 1'b1;
                    if (pb_wr_req) begin
                        axi_awaddr  <= {pb_wr_addr, 4'b0000};
                        axi_awid    <= 4'd1;
                        axi_awlen   <= 8'd0;
                        axi_awsize  <= 3'b100;
                        axi_awburst <= 2'b01;
                        axi_awvalid <= 1'b1;
                        axi_wdata   <= pb_wr_data;
                        axi_wstrb   <= 16'hFFFF;
                        axi_wlast   <= 1'b1;
                        axi_wvalid  <= 1'b1;
                        pb_wr_ready <= 1'b0;
                        wr_state    <= WR_ADDR;
                    end
                end

                WR_ADDR: begin
                    if (axi_awready) axi_awvalid <= 1'b0;
                    if (axi_wready)  axi_wvalid  <= 1'b0;
                    if (!axi_awvalid && !axi_wvalid) begin
                        axi_bready <= 1'b1;
                        wr_state   <= WR_RESP;
                    end
                end

                WR_RESP: begin
                    if (axi_bvalid) begin
                        axi_bready <= 1'b0;
                        wr_state   <= WR_IDLE;
                    end
                end

                default: wr_state <= WR_IDLE;
            endcase
        end
    end

    // ================================================================
    // MIG IP placeholder (tie off for synthesis without IP)
    // ================================================================
    assign ui_clk              = sys_clk_200; // Temporary: use sys_clk
    assign ui_rst_n            = sys_rst_n;
    assign init_calib_complete = 1'b1;        // Pretend ready

    // Stub AXI responses
    assign axi_arready = 1'b1;
    assign axi_rdata   = '0;
    assign axi_rvalid  = axi_arvalid; // Immediate response (stub)
    assign axi_rid     = '0;
    assign axi_rresp   = '0;
    assign axi_rlast   = 1'b1;
    assign axi_awready = 1'b1;
    assign axi_wready  = 1'b1;
    assign axi_bvalid  = 1'b1; // Always ack
    assign axi_bid     = '0;
    assign axi_bresp   = '0;

    // DDR3 physical pins: tie off (MIG IP will drive these)
    assign ddr3_addr    = '0;
    assign ddr3_ba      = '0;
    assign ddr3_ras_n   = 1'b1;
    assign ddr3_cas_n   = 1'b1;
    assign ddr3_we_n    = 1'b1;
    assign ddr3_reset_n = 1'b0;
    assign ddr3_ck_p    = 1'b0;
    assign ddr3_ck_n    = 1'b1;
    assign ddr3_cke     = 1'b0;
    assign ddr3_cs_n    = 1'b1;
    assign ddr3_dm      = '0;
    assign ddr3_odt     = 1'b0;

endmodule
